### ISSUE TITLE
[#0503] Autenticação do usuário

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-web#1]
## 📄 Descrição da atividade

Criar tela de login WEB.

## 🛠 Protótipo

![image](https://user-images.githubusercontent.com/78885451/234127807-0955f07a-9658-4e1a-81c8-d1ccac3e5ce9.png)
![image](https://user-images.githubusercontent.com/78885451/234128080-63a5afb5-ad24-4c82-928e-4222daae0c98.png)

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [x] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [x] Caso a senha esteja incorreta, deve sinalizar conforme protótipo
- [x] Se o e-mail e a senha não forem preenchidos, o botão de login fica desativado
- [x] Se o login for um sucesso, deve ser redirecionado ao dashboard

### DoD: Definition of Done

- [x] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [x] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [x] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [x] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [x] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by ThHenrique** [comment]
# Documentação

## Tecnologias
React JS, axios, SVG, CSS

## Descrição
Tela para autenticação de usuários

## Issues Relacionada
#1  

## Lista de Mudanças

- Nova pagina
- Nova Rota
- Novo arquivo de request (Auth Request)
- Componente de loading
- Componente de Icon


## Checklist
- [x] O código foi testado e está funcionando corretamente
- [x] As mudanças foram revisadas por um colega de equipe
- [x] A documentação foi atualizada, se necessário
- [x] A issue relacionada foi atualizada, se existir
