### ISSUE TITLE
[#0018] Setup web

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-web#2]
## 📄 Descrição da atividade

Realizar setup inicial do projeto WEB.

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points

### Critérios de aceite

- [x] Criação e inicialização do projeto react
- [x] Configurar rota básica
- [x] Instalação de libs e configurações (typescript, styled components, eslint, prettier, etc)
- [x] Criação da estrutura do local storage (pra armazenar os dados do usuário)
- [x] Criação de estrutura de requisições (criar enum de endpoints e service base)

### DoD: Definition of Done

- [x] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [ ] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [x] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [x] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [x] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by drisabelles** [comment]
Adicionados mais itens aos critérios de aceite

**Comment by gioliveirass** [comment]
# Documentação

- URL do projeto: https://owl-partners.netlify.app/auth.

## Tecnologias utilizadas

As seguintes tecnologias foram utilizadas para o setup do projeto: _styled-components, axios, react, react-router-dom e netlify._

## Estrutura do projeto

![Image](https://github.com/The-Bugger-Ducks/owl-partners-web/assets/78885451/94614b66-54b0-45e3-8581-21988e402464)

- **components**: Componentes da aplicação.
- **pages**: Páginas da aplicação.
- **services**: Serviços da aplicação.
- **utils**: Utilitários da aplicação. Atualmente, é dividido em:
   - **controllers**: Controladores da aplicação (Ex.: session controller);
   - **enums**: Enums da aplicação (Ex.: endpoints);
   - **interfaces**: Interfaces da aplicação (Ex.: user);
   - **requests**: Requisições da aplicação (Ex.: dashboard requests).

## Rotas criadas

- **/dashboard**: Página do dashboard.
- **/auth**: Página de autenticação.

## Branchs criadas

- **main**: Branch com o código em produção.
- **development**: Branch com o código em desenvolvimento durante a sprint.
