### ISSUE TITLE
[#0203] Criar componente "menu de navegação"

### ISSUE THREAD

**Issue by gioliveirass** [The-Bugger-Ducks/owl-partners-web#3]
## 📄 Descrição da atividade

Criar componente menu de navegação que aparecerá tanto na tela do dashboard quanto na tela de resultado de análise forecast.

## 🛠 Protótipo

![image](https://user-images.githubusercontent.com/78885451/234132255-04e9593b-80fd-435a-ad2f-13bb0b23e614.png)

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [x] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [x] Ao clicar no botão "Dashnoard", deve abrir a tela de dashboard.
- [ ] Ao clicar no botão "Forecast", deve abrir a tela de resultado de análise forecast.
- [x] Ao clicar no botão "Sair", deve realizar o logout do sistema.

### DoD: Definition of Done

- [ ] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [ ] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [ ] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [ ] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [ ] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by MariaGabrielaReis** [comment]
## Documentação

Foi criado o componente de menu (sidebar - aside).

Tecnologias: React, Styled Components, HTML, CSS

![sidebar](https://github.com/The-Bugger-Ducks/owl-partners-web/assets/69374340/093f67f7-5c54-412b-8a3f-a5cc0288c4ab)

**Comment by gioliveirass** [comment]
@drisabelles essa atividade está prevista para próxima sprint.
