### ISSUE TITLE
[#0204] Criar tela do dashboard

### ISSUE THREAD

**Issue by drisabelles** [The-Bugger-Ducks/owl-partners-web#4]
## 📄 Descrição da atividade

Deve criar tela do dashboard com as seguintes informações:
- Número total de parcerias em desenvolvimento;
- TOP 10 parcerias em desenvolvimento com maior quantidade de membros (vizualição em forma de gráfico de barras);
- Parcerias em desenvolvimento por status (vizualição em forma de gráfico de barras);
- Parcerias em desenvolvimento por estado (vizualição em forma de gráfico de barras);
- Parcerias em desenvolvimento por classificação (vizualição em forma de gráfico de barras);
- Próxima reunião agendada com parceria em desenvolvimento.

Obs.: "Parceria em desenvolvimento" é como o cliente passou a chamar as "Parcerias ativas".

## 🛠 Protótipo

![Image](https://user-images.githubusercontent.com/78885451/234132917-54b9c848-50d2-419f-985f-b9a64fa6b224.png)

### DoR: Definition of Ready

- [x] **Cabe em uma sprint:** De preferência, não deve ser maior que 8 story points
- [x] **Prototipado:** O protótipo já está disponível no [Figma](https://www.figma.com/file/OfE7DUkKkBgC7O3fmDoulH/Owl-Partners-(Oracle)?node-id=11-195&t=txTFGhY0EvM3VWcn-0)
- [x] **Validado com o cliente:** As informações da atividade foram validadas pelo cliente

### Critérios de aceite

- [x] Deve ter o botão "recarregar dashboard", que atualiza as informações apresentadas.
- [x] Deve seguir o protótipo.
- [x] Deve apresentar número total de parcerias em desenvolvimento.
- [x] Deve apresentar TOP 10 parcerias em desenvolvimento com maior quantidade de membros (vizualição em forma de gráfico de barras).
- [x] Deve apresentar parcerias em desenvolvimento por status (vizualição em forma de gráfico de barras).
- [x] Deve apresentar parcerias em desenvolvimento por estado (vizualição em forma de gráfico de barras).
- [x] Deve apresentar parcerias em desenvolvimento por classificação (vizualição em forma de gráfico de barras).
- [x] Deve apresentar próxima reunião agendada com parceria em desenvolvimento.

### DoD: Definition of Done

- [x] **Atende aos critérios de aceite:** Todos os critérios de aceite definidos para a atividade foram cumpridos
- [x] **Code review:** O code review foi realizado e, se identificada a necessidade, as correções foram realizadas
- [x] **Testado e integrado:** A feature desenvolvida já se encontra na branch Development e funciona em harmonia com as demais funcionalidades (navegação em funcionamento, não gerou bugs, conflitos foram resolvidos)
- [x] **Documentado:** A feature desenvolvida foi documentada pelo desenvolvedor
- [x] **Aceito pelo PO:** A feture desenvolvida foi aprovada pelo PO

**Comment by gioliveirass** [comment]
@drisabelles essa atividade está prevista para próxima sprint.

**Comment by drisabelles** [comment]
@gioliveirass movida para a 4a sprint

**Comment by gioliveirass** [comment]
# Documentação

## Tecnologias utilizadas

React, Recharts, Typescript, Axios, Styled-components.

## Demonstração

![Image](https://github.com/The-Bugger-Ducks/owl-partners-web/assets/78885451/99592378-0c1a-4a75-90c6-345ba617f07a)
